spring:
#  datasource:
#    url: jdbc:mysql://47.106.189.30:3306/oo?useSSL=false
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
  datasource:
    platform: h2
##    schema: classpath:schema.sql
    data: classpath:data.sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
    